name: Actualizar datos de futbol
on:
  schedule:
    - cron: '*/30 * * * *' # Se ejecuta cada 30 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requests
        run: pip install requests
      - name: Fetch data
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python fetch_data.py
      - name: Commit data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json
          git commit -m "Actualizacion automatica de resultados" || exit 0
          git push
